name: "automated-tests"
on: [push, pull_request]
jobs:
  build:
    name: "Build project"
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: test
        run: mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && cmake --build . && ctest