name: "automated-tests"
on: [push, pull_request]
jobs:
  build:
    name: "Build project"
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - id: build-on-windows
        if: matrix.operating-system == 'windows-latest'
        run: mkdir build && cd build && cmake .. && cmake --build . --target INSTALL
      - id: tests-for-mac-and-linux
        if: matrix.operating-system == 'macos-latest' || matrix.operating-system == 'ubuntu-20.04'
        run: mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && cmake --build . && ctest